spring:
  application:
    name: memberserver
  datasource:
    password: golpe123321
    username: root
    url: jdbc:mysql://121.41.229.45:3306/shh-member?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8011
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    lease-renewal-interval-in-seconds: 30


